### ISSUE TITLE
GUI design

### ISSUE THREAD

**Issue by thedement0r** [TIS2024-FMFI/vehicle-delivery#11]
Testing technologies and making the first draft

**Comment by Hrodo** [comment]
[Formular.zip](https://github.com/user-attachments/files/17821201/Formular.zip)

first form version done by @PeterDuska

**Comment by PeterDuska** [comment]
![4](https://github.com/user-attachments/assets/71103b55-2bbe-4958-8852-7fab8d2945d1)
![3](https://github.com/user-attachments/assets/fe78c58f-3f39-48bb-bec0-8e57baef9fb2)
![2](https://github.com/user-attachments/assets/43e6eade-4fbc-44f1-b08d-137851595510)
![1](https://github.com/user-attachments/assets/e02d198f-3ae4-433d-ade9-e46d7c11c1bf)

**Comment by Hrodo** [comment]
looks good, I think we could include some way to download all pictures at once.

**Comment by PeterDuska** [comment]
![Image](https://github.com/user-attachments/assets/d4d99fc7-0b5a-40eb-9fe6-818ef1390e3e)
Added button at the top of the report
