### ISSUE TITLE
Collection of project requirements

### ISSUE THREAD

**Issue by Hrodo** [TIS2024-FMFI/vehicle-delivery#2]
Collecting project requirements from a meeting with customer

**Comment by pavelpetrovic** [comment]
29.10.
vsetci pritomni
zapisnica je fajn a prosim pisat agendu a zapis zo stretnutia zvlast postupne
issues ako tak funguju, ale nie som si isty, ci pokryvaju ulohy navrhu dostatocne
citame si hadam finalny KP
mame kontakt na technika, treba mu este napisat
KP este prosim zlepsit dosledne a potom odoslat zadavatelovi na spripomienkovanie
