### ISSUE TITLE
Component diagram

### ISSUE THREAD

**Issue by Vi-Mi** [TIS2024-FMFI/vehicle-delivery#20]

**Comment by PeterDuska** [comment]
![Image](https://github.com/user-attachments/assets/32f31b8f-90b4-4001-ad3c-94b5dddc2de5)

**Comment by Vi-Mi** [comment]
Looks good. Just add text to it

**Comment by PeterDuska** [comment]
![Image](https://github.com/user-attachments/assets/f9879075-94ed-4fa9-90e0-9879f20269de)
