### ISSUE TITLE
Sequence diagram

### ISSUE THREAD

**Issue by Vi-Mi** [TIS2024-FMFI/vehicle-delivery#21]

**Comment by thedement0r** [comment]
![Image](https://github.com/user-attachments/assets/beff4566-c4f6-4d34-a9ee-189be04d20d4)

**Comment by thedement0r** [comment]
![Agent Viewing Complaints](https://github.com/user-attachments/assets/8276b0a6-e2ac-4545-a60f-5c384e64039c)
Scenario : Agent Viewing Complaints

**Comment by thedement0r** [comment]
![New_Sequence](https://github.com/user-attachments/assets/f46da957-7fd1-4ad9-b7a7-af60d002d0d6)
